package com.twq.dao.model;

public class ContentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.share_img
     *
     * @mbg.generated
     */
    private String shareImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.sub_title
     *
     * @mbg.generated
     */
    private String subTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.how_to_play
     *
     * @mbg.generated
     */
    private String howToPlay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.content
     *
     * @return the value of content.content
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.content
     *
     * @param content the value for content.content
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.share_img
     *
     * @return the value of content.share_img
     * @mbg.generated
     */
    public String getShareImg() {
        return shareImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.share_img
     *
     * @param shareImg the value for content.share_img
     * @mbg.generated
     */
    public void setShareImg(String shareImg) {
        this.shareImg = shareImg == null ? null : shareImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.sub_title
     *
     * @return the value of content.sub_title
     * @mbg.generated
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.sub_title
     *
     * @param subTitle the value for content.sub_title
     * @mbg.generated
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.how_to_play
     *
     * @return the value of content.how_to_play
     * @mbg.generated
     */
    public String getHowToPlay() {
        return howToPlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.how_to_play
     *
     * @param howToPlay the value for content.how_to_play
     * @mbg.generated
     */
    public void setHowToPlay(String howToPlay) {
        this.howToPlay = howToPlay == null ? null : howToPlay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.title
     *
     * @return the value of content.title
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.title
     *
     * @param title the value for content.title
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}