package com.twq.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class Games {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games.check_in_time
     *
     * @mbg.generated
     */
    private Date checkInTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games.party_time
     *
     * @mbg.generated
     */
    private String partyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games.check_money
     *
     * @mbg.generated
     */
    private BigDecimal checkMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games.is_recheck
     *
     * @mbg.generated
     */
    private Byte isRecheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games.re_checkTime
     *
     * @mbg.generated
     */
    private Date reChecktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column games.re_checkMoney
     *
     * @mbg.generated
     */
    private BigDecimal reCheckmoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games.id
     *
     * @return the value of games.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games.id
     *
     * @param id the value for games.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games.user_id
     *
     * @return the value of games.user_id
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games.user_id
     *
     * @param userId the value for games.user_id
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games.check_in_time
     *
     * @return the value of games.check_in_time
     * @mbg.generated
     */
    public Date getCheckInTime() {
        return checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games.check_in_time
     *
     * @param checkInTime the value for games.check_in_time
     * @mbg.generated
     */
    public void setCheckInTime(Date checkInTime) {
        this.checkInTime = checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games.party_time
     *
     * @return the value of games.party_time
     * @mbg.generated
     */
    public String getPartyTime() {
        return partyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games.party_time
     *
     * @param partyTime the value for games.party_time
     * @mbg.generated
     */
    public void setPartyTime(String partyTime) {
        this.partyTime = partyTime == null ? null : partyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games.check_money
     *
     * @return the value of games.check_money
     * @mbg.generated
     */
    public BigDecimal getCheckMoney() {
        return checkMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games.check_money
     *
     * @param checkMoney the value for games.check_money
     * @mbg.generated
     */
    public void setCheckMoney(BigDecimal checkMoney) {
        this.checkMoney = checkMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games.is_recheck
     *
     * @return the value of games.is_recheck
     * @mbg.generated
     */
    public Byte getIsRecheck() {
        return isRecheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games.is_recheck
     *
     * @param isRecheck the value for games.is_recheck
     * @mbg.generated
     */
    public void setIsRecheck(Byte isRecheck) {
        this.isRecheck = isRecheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games.re_checkTime
     *
     * @return the value of games.re_checkTime
     * @mbg.generated
     */
    public Date getReChecktime() {
        return reChecktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games.re_checkTime
     *
     * @param reChecktime the value for games.re_checkTime
     * @mbg.generated
     */
    public void setReChecktime(Date reChecktime) {
        this.reChecktime = reChecktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column games.re_checkMoney
     *
     * @return the value of games.re_checkMoney
     * @mbg.generated
     */
    public BigDecimal getReCheckmoney() {
        return reCheckmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column games.re_checkMoney
     *
     * @param reCheckmoney the value for games.re_checkMoney
     * @mbg.generated
     */
    public void setReCheckmoney(BigDecimal reCheckmoney) {
        this.reCheckmoney = reCheckmoney;
    }
}