package com.twq.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class GameWallet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_wallet.game_money
     *
     * @mbg.generated
     */
    private BigDecimal gameMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_wallet.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_wallet.game_money
     *
     * @return the value of game_wallet.game_money
     * @mbg.generated
     */
    public BigDecimal getGameMoney() {
        return gameMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_wallet.game_money
     *
     * @param gameMoney the value for game_wallet.game_money
     * @mbg.generated
     */
    public void setGameMoney(BigDecimal gameMoney) {
        this.gameMoney = gameMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_wallet.update_at
     *
     * @return the value of game_wallet.update_at
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_wallet.update_at
     *
     * @param updateAt the value for game_wallet.update_at
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}