package com.twq.dao.model;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_name
     *
     * @mbg.generated
     */
    private String orderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.attach
     *
     * @mbg.generated
     */
    private String attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.out_trade_no
     *
     * @mbg.generated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.fee_type
     *
     * @mbg.generated
     */
    private String feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.total_fee
     *
     * @mbg.generated
     */
    private Integer totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.spbill_create_ip
     *
     * @mbg.generated
     */
    private String spbillCreateIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.time_start
     *
     * @mbg.generated
     */
    private String timeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.time_expire
     *
     * @mbg.generated
     */
    private String timeExpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.trade_type
     *
     * @mbg.generated
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order_info.order_id
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_name
     *
     * @return the value of order_info.order_name
     * @mbg.generated
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_name
     *
     * @param orderName the value for order_info.order_name
     * @mbg.generated
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName == null ? null : orderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.attach
     *
     * @return the value of order_info.attach
     * @mbg.generated
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.attach
     *
     * @param attach the value for order_info.attach
     * @mbg.generated
     */
    public void setAttach(String attach) {
        this.attach = attach == null ? null : attach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.out_trade_no
     *
     * @return the value of order_info.out_trade_no
     * @mbg.generated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.out_trade_no
     *
     * @param outTradeNo the value for order_info.out_trade_no
     * @mbg.generated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.fee_type
     *
     * @return the value of order_info.fee_type
     * @mbg.generated
     */
    public String getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.fee_type
     *
     * @param feeType the value for order_info.fee_type
     * @mbg.generated
     */
    public void setFeeType(String feeType) {
        this.feeType = feeType == null ? null : feeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.total_fee
     *
     * @return the value of order_info.total_fee
     * @mbg.generated
     */
    public Integer getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.total_fee
     *
     * @param totalFee the value for order_info.total_fee
     * @mbg.generated
     */
    public void setTotalFee(Integer totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.spbill_create_ip
     *
     * @return the value of order_info.spbill_create_ip
     * @mbg.generated
     */
    public String getSpbillCreateIp() {
        return spbillCreateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.spbill_create_ip
     *
     * @param spbillCreateIp the value for order_info.spbill_create_ip
     * @mbg.generated
     */
    public void setSpbillCreateIp(String spbillCreateIp) {
        this.spbillCreateIp = spbillCreateIp == null ? null : spbillCreateIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.time_start
     *
     * @return the value of order_info.time_start
     * @mbg.generated
     */
    public String getTimeStart() {
        return timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.time_start
     *
     * @param timeStart the value for order_info.time_start
     * @mbg.generated
     */
    public void setTimeStart(String timeStart) {
        this.timeStart = timeStart == null ? null : timeStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.time_expire
     *
     * @return the value of order_info.time_expire
     * @mbg.generated
     */
    public String getTimeExpire() {
        return timeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.time_expire
     *
     * @param timeExpire the value for order_info.time_expire
     * @mbg.generated
     */
    public void setTimeExpire(String timeExpire) {
        this.timeExpire = timeExpire == null ? null : timeExpire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.trade_type
     *
     * @return the value of order_info.trade_type
     * @mbg.generated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.trade_type
     *
     * @param tradeType the value for order_info.trade_type
     * @mbg.generated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.product_id
     *
     * @return the value of order_info.product_id
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.product_id
     *
     * @param productId the value for order_info.product_id
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.openid
     *
     * @return the value of order_info.openid
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.openid
     *
     * @param openid the value for order_info.openid
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }
}