package com.twq.dao.model;

public class Parameters {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.param_key
     *
     * @mbg.generated
     */
    private String paramKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.param_value
     *
     * @mbg.generated
     */
    private String paramValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.param_desc
     *
     * @mbg.generated
     */
    private String paramDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameters.param_type
     *
     * @mbg.generated
     */
    private String paramType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.param_key
     *
     * @return the value of parameters.param_key
     *
     * @mbg.generated
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.param_key
     *
     * @param paramKey the value for parameters.param_key
     *
     * @mbg.generated
     */
    public void setParamKey(String paramKey) {
        this.paramKey = paramKey == null ? null : paramKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.param_value
     *
     * @return the value of parameters.param_value
     *
     * @mbg.generated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.param_value
     *
     * @param paramValue the value for parameters.param_value
     *
     * @mbg.generated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.param_desc
     *
     * @return the value of parameters.param_desc
     *
     * @mbg.generated
     */
    public String getParamDesc() {
        return paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.param_desc
     *
     * @param paramDesc the value for parameters.param_desc
     *
     * @mbg.generated
     */
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc == null ? null : paramDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameters.param_type
     *
     * @return the value of parameters.param_type
     *
     * @mbg.generated
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameters.param_type
     *
     * @param paramType the value for parameters.param_type
     *
     * @mbg.generated
     */
    public void setParamType(String paramType) {
        this.paramType = paramType == null ? null : paramType.trim();
    }
}