package com.twq.dao.model;

public class ProjectInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_img
     *
     * @mbg.generated
     */
    private String projectImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.background_img
     *
     * @mbg.generated
     */
    private String backgroundImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.cover_color
     *
     * @mbg.generated
     */
    private String coverColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.cover_img_id
     *
     * @mbg.generated
     */
    private Integer coverImgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_type
     *
     * @mbg.generated
     */
    private Integer projectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.rule
     *
     * @mbg.generated
     */
    private Integer rule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.share_url
     *
     * @mbg.generated
     */
    private String shareUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.create_amount
     *
     * @mbg.generated
     */
    private Integer createAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.game_mode
     *
     * @mbg.generated
     */
    private Integer gameMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.join_amount
     *
     * @mbg.generated
     */
    private Integer joinAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.ad_img
     *
     * @mbg.generated
     */
    private String adImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.ad_url
     *
     * @mbg.generated
     */
    private String adUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.start_time
     *
     * @mbg.generated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.end_time
     *
     * @mbg.generated
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.start_date
     *
     * @mbg.generated
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.end_date
     *
     * @mbg.generated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.period_length
     *
     * @mbg.generated
     */
    private Double periodLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.cityid
     *
     * @mbg.generated
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.renew_time
     *
     * @mbg.generated
     */
    private String renewTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.weekdays
     *
     * @mbg.generated
     */
    private String weekdays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.lat_lon
     *
     * @mbg.generated
     */
    private String latLon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.addr_range
     *
     * @mbg.generated
     */
    private String addrRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.fake_amount
     *
     * @mbg.generated
     */
    private Integer fakeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.fake_success_percentage
     *
     * @mbg.generated
     */
    private Integer fakeSuccessPercentage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.is_hide
     *
     * @mbg.generated
     */
    private Integer isHide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.recommend
     *
     * @mbg.generated
     */
    private Integer recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.privalage
     *
     * @mbg.generated
     */
    private Integer privalage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.id
     *
     * @return the value of project_info.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.id
     *
     * @param id the value for project_info.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_name
     *
     * @return the value of project_info.project_name
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_name
     *
     * @param projectName the value for project_info.project_name
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_img
     *
     * @return the value of project_info.project_img
     * @mbg.generated
     */
    public String getProjectImg() {
        return projectImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_img
     *
     * @param projectImg the value for project_info.project_img
     * @mbg.generated
     */
    public void setProjectImg(String projectImg) {
        this.projectImg = projectImg == null ? null : projectImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.background_img
     *
     * @return the value of project_info.background_img
     * @mbg.generated
     */
    public String getBackgroundImg() {
        return backgroundImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.background_img
     *
     * @param backgroundImg the value for project_info.background_img
     * @mbg.generated
     */
    public void setBackgroundImg(String backgroundImg) {
        this.backgroundImg = backgroundImg == null ? null : backgroundImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.cover_color
     *
     * @return the value of project_info.cover_color
     * @mbg.generated
     */
    public String getCoverColor() {
        return coverColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.cover_color
     *
     * @param coverColor the value for project_info.cover_color
     * @mbg.generated
     */
    public void setCoverColor(String coverColor) {
        this.coverColor = coverColor == null ? null : coverColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.cover_img_id
     *
     * @return the value of project_info.cover_img_id
     * @mbg.generated
     */
    public Integer getCoverImgId() {
        return coverImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.cover_img_id
     *
     * @param coverImgId the value for project_info.cover_img_id
     * @mbg.generated
     */
    public void setCoverImgId(Integer coverImgId) {
        this.coverImgId = coverImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_type
     *
     * @return the value of project_info.project_type
     * @mbg.generated
     */
    public Integer getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_type
     *
     * @param projectType the value for project_info.project_type
     * @mbg.generated
     */
    public void setProjectType(Integer projectType) {
        this.projectType = projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.introduction
     *
     * @return the value of project_info.introduction
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.introduction
     *
     * @param introduction the value for project_info.introduction
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.rule
     *
     * @return the value of project_info.rule
     * @mbg.generated
     */
    public Integer getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.rule
     *
     * @param rule the value for project_info.rule
     * @mbg.generated
     */
    public void setRule(Integer rule) {
        this.rule = rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.share_url
     *
     * @return the value of project_info.share_url
     * @mbg.generated
     */
    public String getShareUrl() {
        return shareUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.share_url
     *
     * @param shareUrl the value for project_info.share_url
     * @mbg.generated
     */
    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl == null ? null : shareUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.create_amount
     *
     * @return the value of project_info.create_amount
     * @mbg.generated
     */
    public Integer getCreateAmount() {
        return createAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.create_amount
     *
     * @param createAmount the value for project_info.create_amount
     * @mbg.generated
     */
    public void setCreateAmount(Integer createAmount) {
        this.createAmount = createAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.game_mode
     *
     * @return the value of project_info.game_mode
     * @mbg.generated
     */
    public Integer getGameMode() {
        return gameMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.game_mode
     *
     * @param gameMode the value for project_info.game_mode
     * @mbg.generated
     */
    public void setGameMode(Integer gameMode) {
        this.gameMode = gameMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.join_amount
     *
     * @return the value of project_info.join_amount
     * @mbg.generated
     */
    public Integer getJoinAmount() {
        return joinAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.join_amount
     *
     * @param joinAmount the value for project_info.join_amount
     * @mbg.generated
     */
    public void setJoinAmount(Integer joinAmount) {
        this.joinAmount = joinAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.ad_img
     *
     * @return the value of project_info.ad_img
     * @mbg.generated
     */
    public String getAdImg() {
        return adImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.ad_img
     *
     * @param adImg the value for project_info.ad_img
     * @mbg.generated
     */
    public void setAdImg(String adImg) {
        this.adImg = adImg == null ? null : adImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.ad_url
     *
     * @return the value of project_info.ad_url
     * @mbg.generated
     */
    public String getAdUrl() {
        return adUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.ad_url
     *
     * @param adUrl the value for project_info.ad_url
     * @mbg.generated
     */
    public void setAdUrl(String adUrl) {
        this.adUrl = adUrl == null ? null : adUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.start_time
     *
     * @return the value of project_info.start_time
     * @mbg.generated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.start_time
     *
     * @param startTime the value for project_info.start_time
     * @mbg.generated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.end_time
     *
     * @return the value of project_info.end_time
     * @mbg.generated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.end_time
     *
     * @param endTime the value for project_info.end_time
     * @mbg.generated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.start_date
     *
     * @return the value of project_info.start_date
     * @mbg.generated
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.start_date
     *
     * @param startDate the value for project_info.start_date
     * @mbg.generated
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.end_date
     *
     * @return the value of project_info.end_date
     * @mbg.generated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.end_date
     *
     * @param endDate the value for project_info.end_date
     * @mbg.generated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.period_length
     *
     * @return the value of project_info.period_length
     * @mbg.generated
     */
    public Double getPeriodLength() {
        return periodLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.period_length
     *
     * @param periodLength the value for project_info.period_length
     * @mbg.generated
     */
    public void setPeriodLength(Double periodLength) {
        this.periodLength = periodLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.cityid
     *
     * @return the value of project_info.cityid
     * @mbg.generated
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.cityid
     *
     * @param cityid the value for project_info.cityid
     * @mbg.generated
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.renew_time
     *
     * @return the value of project_info.renew_time
     * @mbg.generated
     */
    public String getRenewTime() {
        return renewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.renew_time
     *
     * @param renewTime the value for project_info.renew_time
     * @mbg.generated
     */
    public void setRenewTime(String renewTime) {
        this.renewTime = renewTime == null ? null : renewTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.weekdays
     *
     * @return the value of project_info.weekdays
     * @mbg.generated
     */
    public String getWeekdays() {
        return weekdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.weekdays
     *
     * @param weekdays the value for project_info.weekdays
     * @mbg.generated
     */
    public void setWeekdays(String weekdays) {
        this.weekdays = weekdays == null ? null : weekdays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.address
     *
     * @return the value of project_info.address
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.address
     *
     * @param address the value for project_info.address
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.lat_lon
     *
     * @return the value of project_info.lat_lon
     * @mbg.generated
     */
    public String getLatLon() {
        return latLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.lat_lon
     *
     * @param latLon the value for project_info.lat_lon
     * @mbg.generated
     */
    public void setLatLon(String latLon) {
        this.latLon = latLon == null ? null : latLon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.addr_range
     *
     * @return the value of project_info.addr_range
     * @mbg.generated
     */
    public String getAddrRange() {
        return addrRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.addr_range
     *
     * @param addrRange the value for project_info.addr_range
     * @mbg.generated
     */
    public void setAddrRange(String addrRange) {
        this.addrRange = addrRange == null ? null : addrRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.fake_amount
     *
     * @return the value of project_info.fake_amount
     * @mbg.generated
     */
    public Integer getFakeAmount() {
        return fakeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.fake_amount
     *
     * @param fakeAmount the value for project_info.fake_amount
     * @mbg.generated
     */
    public void setFakeAmount(Integer fakeAmount) {
        this.fakeAmount = fakeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.fake_success_percentage
     *
     * @return the value of project_info.fake_success_percentage
     * @mbg.generated
     */
    public Integer getFakeSuccessPercentage() {
        return fakeSuccessPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.fake_success_percentage
     *
     * @param fakeSuccessPercentage the value for project_info.fake_success_percentage
     * @mbg.generated
     */
    public void setFakeSuccessPercentage(Integer fakeSuccessPercentage) {
        this.fakeSuccessPercentage = fakeSuccessPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.is_hide
     *
     * @return the value of project_info.is_hide
     * @mbg.generated
     */
    public Integer getIsHide() {
        return isHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.is_hide
     *
     * @param isHide the value for project_info.is_hide
     * @mbg.generated
     */
    public void setIsHide(Integer isHide) {
        this.isHide = isHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.sort
     *
     * @return the value of project_info.sort
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.sort
     *
     * @param sort the value for project_info.sort
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.recommend
     *
     * @return the value of project_info.recommend
     * @mbg.generated
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.recommend
     *
     * @param recommend the value for project_info.recommend
     * @mbg.generated
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.privalage
     *
     * @return the value of project_info.privalage
     * @mbg.generated
     */
    public Integer getPrivalage() {
        return privalage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.privalage
     *
     * @param privalage the value for project_info.privalage
     * @mbg.generated
     */
    public void setPrivalage(Integer privalage) {
        this.privalage = privalage;
    }
}