package com.twq.dao.model;

import java.util.ArrayList;
import java.util.List;

public class ProjectInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated
     */
    public ProjectInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("project_name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("project_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("project_name =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("project_name <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("project_name >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("project_name >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("project_name <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("project_name <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("project_name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("project_name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("project_name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("project_name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("project_name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("project_name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectImgIsNull() {
            addCriterion("project_img is null");
            return (Criteria) this;
        }

        public Criteria andProjectImgIsNotNull() {
            addCriterion("project_img is not null");
            return (Criteria) this;
        }

        public Criteria andProjectImgEqualTo(String value) {
            addCriterion("project_img =", value, "projectImg");
            return (Criteria) this;
        }

        public Criteria andProjectImgNotEqualTo(String value) {
            addCriterion("project_img <>", value, "projectImg");
            return (Criteria) this;
        }

        public Criteria andProjectImgGreaterThan(String value) {
            addCriterion("project_img >", value, "projectImg");
            return (Criteria) this;
        }

        public Criteria andProjectImgGreaterThanOrEqualTo(String value) {
            addCriterion("project_img >=", value, "projectImg");
            return (Criteria) this;
        }

        public Criteria andProjectImgLessThan(String value) {
            addCriterion("project_img <", value, "projectImg");
            return (Criteria) this;
        }

        public Criteria andProjectImgLessThanOrEqualTo(String value) {
            addCriterion("project_img <=", value, "projectImg");
            return (Criteria) this;
        }

        public Criteria andProjectImgLike(String value) {
            addCriterion("project_img like", value, "projectImg");
            return (Criteria) this;
        }

        public Criteria andProjectImgNotLike(String value) {
            addCriterion("project_img not like", value, "projectImg");
            return (Criteria) this;
        }

        public Criteria andProjectImgIn(List<String> values) {
            addCriterion("project_img in", values, "projectImg");
            return (Criteria) this;
        }

        public Criteria andProjectImgNotIn(List<String> values) {
            addCriterion("project_img not in", values, "projectImg");
            return (Criteria) this;
        }

        public Criteria andProjectImgBetween(String value1, String value2) {
            addCriterion("project_img between", value1, value2, "projectImg");
            return (Criteria) this;
        }

        public Criteria andProjectImgNotBetween(String value1, String value2) {
            addCriterion("project_img not between", value1, value2, "projectImg");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgIsNull() {
            addCriterion("background_img is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgIsNotNull() {
            addCriterion("background_img is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgEqualTo(String value) {
            addCriterion("background_img =", value, "backgroundImg");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgNotEqualTo(String value) {
            addCriterion("background_img <>", value, "backgroundImg");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgGreaterThan(String value) {
            addCriterion("background_img >", value, "backgroundImg");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgGreaterThanOrEqualTo(String value) {
            addCriterion("background_img >=", value, "backgroundImg");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgLessThan(String value) {
            addCriterion("background_img <", value, "backgroundImg");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgLessThanOrEqualTo(String value) {
            addCriterion("background_img <=", value, "backgroundImg");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgLike(String value) {
            addCriterion("background_img like", value, "backgroundImg");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgNotLike(String value) {
            addCriterion("background_img not like", value, "backgroundImg");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgIn(List<String> values) {
            addCriterion("background_img in", values, "backgroundImg");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgNotIn(List<String> values) {
            addCriterion("background_img not in", values, "backgroundImg");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgBetween(String value1, String value2) {
            addCriterion("background_img between", value1, value2, "backgroundImg");
            return (Criteria) this;
        }

        public Criteria andBackgroundImgNotBetween(String value1, String value2) {
            addCriterion("background_img not between", value1, value2, "backgroundImg");
            return (Criteria) this;
        }

        public Criteria andCoverColorIsNull() {
            addCriterion("cover_color is null");
            return (Criteria) this;
        }

        public Criteria andCoverColorIsNotNull() {
            addCriterion("cover_color is not null");
            return (Criteria) this;
        }

        public Criteria andCoverColorEqualTo(String value) {
            addCriterion("cover_color =", value, "coverColor");
            return (Criteria) this;
        }

        public Criteria andCoverColorNotEqualTo(String value) {
            addCriterion("cover_color <>", value, "coverColor");
            return (Criteria) this;
        }

        public Criteria andCoverColorGreaterThan(String value) {
            addCriterion("cover_color >", value, "coverColor");
            return (Criteria) this;
        }

        public Criteria andCoverColorGreaterThanOrEqualTo(String value) {
            addCriterion("cover_color >=", value, "coverColor");
            return (Criteria) this;
        }

        public Criteria andCoverColorLessThan(String value) {
            addCriterion("cover_color <", value, "coverColor");
            return (Criteria) this;
        }

        public Criteria andCoverColorLessThanOrEqualTo(String value) {
            addCriterion("cover_color <=", value, "coverColor");
            return (Criteria) this;
        }

        public Criteria andCoverColorLike(String value) {
            addCriterion("cover_color like", value, "coverColor");
            return (Criteria) this;
        }

        public Criteria andCoverColorNotLike(String value) {
            addCriterion("cover_color not like", value, "coverColor");
            return (Criteria) this;
        }

        public Criteria andCoverColorIn(List<String> values) {
            addCriterion("cover_color in", values, "coverColor");
            return (Criteria) this;
        }

        public Criteria andCoverColorNotIn(List<String> values) {
            addCriterion("cover_color not in", values, "coverColor");
            return (Criteria) this;
        }

        public Criteria andCoverColorBetween(String value1, String value2) {
            addCriterion("cover_color between", value1, value2, "coverColor");
            return (Criteria) this;
        }

        public Criteria andCoverColorNotBetween(String value1, String value2) {
            addCriterion("cover_color not between", value1, value2, "coverColor");
            return (Criteria) this;
        }

        public Criteria andCoverImgIdIsNull() {
            addCriterion("cover_img_id is null");
            return (Criteria) this;
        }

        public Criteria andCoverImgIdIsNotNull() {
            addCriterion("cover_img_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImgIdEqualTo(Integer value) {
            addCriterion("cover_img_id =", value, "coverImgId");
            return (Criteria) this;
        }

        public Criteria andCoverImgIdNotEqualTo(Integer value) {
            addCriterion("cover_img_id <>", value, "coverImgId");
            return (Criteria) this;
        }

        public Criteria andCoverImgIdGreaterThan(Integer value) {
            addCriterion("cover_img_id >", value, "coverImgId");
            return (Criteria) this;
        }

        public Criteria andCoverImgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cover_img_id >=", value, "coverImgId");
            return (Criteria) this;
        }

        public Criteria andCoverImgIdLessThan(Integer value) {
            addCriterion("cover_img_id <", value, "coverImgId");
            return (Criteria) this;
        }

        public Criteria andCoverImgIdLessThanOrEqualTo(Integer value) {
            addCriterion("cover_img_id <=", value, "coverImgId");
            return (Criteria) this;
        }

        public Criteria andCoverImgIdIn(List<Integer> values) {
            addCriterion("cover_img_id in", values, "coverImgId");
            return (Criteria) this;
        }

        public Criteria andCoverImgIdNotIn(List<Integer> values) {
            addCriterion("cover_img_id not in", values, "coverImgId");
            return (Criteria) this;
        }

        public Criteria andCoverImgIdBetween(Integer value1, Integer value2) {
            addCriterion("cover_img_id between", value1, value2, "coverImgId");
            return (Criteria) this;
        }

        public Criteria andCoverImgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cover_img_id not between", value1, value2, "coverImgId");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIsNull() {
            addCriterion("project_type is null");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIsNotNull() {
            addCriterion("project_type is not null");
            return (Criteria) this;
        }

        public Criteria andProjectTypeEqualTo(Integer value) {
            addCriterion("project_type =", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotEqualTo(Integer value) {
            addCriterion("project_type <>", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeGreaterThan(Integer value) {
            addCriterion("project_type >", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_type >=", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLessThan(Integer value) {
            addCriterion("project_type <", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLessThanOrEqualTo(Integer value) {
            addCriterion("project_type <=", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIn(List<Integer> values) {
            addCriterion("project_type in", values, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotIn(List<Integer> values) {
            addCriterion("project_type not in", values, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeBetween(Integer value1, Integer value2) {
            addCriterion("project_type between", value1, value2, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("project_type not between", value1, value2, "projectType");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNull() {
            addCriterion("introduction is null");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNotNull() {
            addCriterion("introduction is not null");
            return (Criteria) this;
        }

        public Criteria andIntroductionEqualTo(String value) {
            addCriterion("introduction =", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotEqualTo(String value) {
            addCriterion("introduction <>", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThan(String value) {
            addCriterion("introduction >", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("introduction >=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThan(String value) {
            addCriterion("introduction <", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThanOrEqualTo(String value) {
            addCriterion("introduction <=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLike(String value) {
            addCriterion("introduction like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotLike(String value) {
            addCriterion("introduction not like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionIn(List<String> values) {
            addCriterion("introduction in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotIn(List<String> values) {
            addCriterion("introduction not in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionBetween(String value1, String value2) {
            addCriterion("introduction between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotBetween(String value1, String value2) {
            addCriterion("introduction not between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andRuleIsNull() {
            addCriterion("rule is null");
            return (Criteria) this;
        }

        public Criteria andRuleIsNotNull() {
            addCriterion("rule is not null");
            return (Criteria) this;
        }

        public Criteria andRuleEqualTo(Integer value) {
            addCriterion("rule =", value, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleNotEqualTo(Integer value) {
            addCriterion("rule <>", value, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleGreaterThan(Integer value) {
            addCriterion("rule >", value, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleGreaterThanOrEqualTo(Integer value) {
            addCriterion("rule >=", value, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleLessThan(Integer value) {
            addCriterion("rule <", value, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleLessThanOrEqualTo(Integer value) {
            addCriterion("rule <=", value, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleIn(List<Integer> values) {
            addCriterion("rule in", values, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleNotIn(List<Integer> values) {
            addCriterion("rule not in", values, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleBetween(Integer value1, Integer value2) {
            addCriterion("rule between", value1, value2, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleNotBetween(Integer value1, Integer value2) {
            addCriterion("rule not between", value1, value2, "rule");
            return (Criteria) this;
        }

        public Criteria andShareUrlIsNull() {
            addCriterion("share_url is null");
            return (Criteria) this;
        }

        public Criteria andShareUrlIsNotNull() {
            addCriterion("share_url is not null");
            return (Criteria) this;
        }

        public Criteria andShareUrlEqualTo(String value) {
            addCriterion("share_url =", value, "shareUrl");
            return (Criteria) this;
        }

        public Criteria andShareUrlNotEqualTo(String value) {
            addCriterion("share_url <>", value, "shareUrl");
            return (Criteria) this;
        }

        public Criteria andShareUrlGreaterThan(String value) {
            addCriterion("share_url >", value, "shareUrl");
            return (Criteria) this;
        }

        public Criteria andShareUrlGreaterThanOrEqualTo(String value) {
            addCriterion("share_url >=", value, "shareUrl");
            return (Criteria) this;
        }

        public Criteria andShareUrlLessThan(String value) {
            addCriterion("share_url <", value, "shareUrl");
            return (Criteria) this;
        }

        public Criteria andShareUrlLessThanOrEqualTo(String value) {
            addCriterion("share_url <=", value, "shareUrl");
            return (Criteria) this;
        }

        public Criteria andShareUrlLike(String value) {
            addCriterion("share_url like", value, "shareUrl");
            return (Criteria) this;
        }

        public Criteria andShareUrlNotLike(String value) {
            addCriterion("share_url not like", value, "shareUrl");
            return (Criteria) this;
        }

        public Criteria andShareUrlIn(List<String> values) {
            addCriterion("share_url in", values, "shareUrl");
            return (Criteria) this;
        }

        public Criteria andShareUrlNotIn(List<String> values) {
            addCriterion("share_url not in", values, "shareUrl");
            return (Criteria) this;
        }

        public Criteria andShareUrlBetween(String value1, String value2) {
            addCriterion("share_url between", value1, value2, "shareUrl");
            return (Criteria) this;
        }

        public Criteria andShareUrlNotBetween(String value1, String value2) {
            addCriterion("share_url not between", value1, value2, "shareUrl");
            return (Criteria) this;
        }

        public Criteria andCreateAmountIsNull() {
            addCriterion("create_amount is null");
            return (Criteria) this;
        }

        public Criteria andCreateAmountIsNotNull() {
            addCriterion("create_amount is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAmountEqualTo(Integer value) {
            addCriterion("create_amount =", value, "createAmount");
            return (Criteria) this;
        }

        public Criteria andCreateAmountNotEqualTo(Integer value) {
            addCriterion("create_amount <>", value, "createAmount");
            return (Criteria) this;
        }

        public Criteria andCreateAmountGreaterThan(Integer value) {
            addCriterion("create_amount >", value, "createAmount");
            return (Criteria) this;
        }

        public Criteria andCreateAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_amount >=", value, "createAmount");
            return (Criteria) this;
        }

        public Criteria andCreateAmountLessThan(Integer value) {
            addCriterion("create_amount <", value, "createAmount");
            return (Criteria) this;
        }

        public Criteria andCreateAmountLessThanOrEqualTo(Integer value) {
            addCriterion("create_amount <=", value, "createAmount");
            return (Criteria) this;
        }

        public Criteria andCreateAmountIn(List<Integer> values) {
            addCriterion("create_amount in", values, "createAmount");
            return (Criteria) this;
        }

        public Criteria andCreateAmountNotIn(List<Integer> values) {
            addCriterion("create_amount not in", values, "createAmount");
            return (Criteria) this;
        }

        public Criteria andCreateAmountBetween(Integer value1, Integer value2) {
            addCriterion("create_amount between", value1, value2, "createAmount");
            return (Criteria) this;
        }

        public Criteria andCreateAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("create_amount not between", value1, value2, "createAmount");
            return (Criteria) this;
        }

        public Criteria andGameModeIsNull() {
            addCriterion("game_mode is null");
            return (Criteria) this;
        }

        public Criteria andGameModeIsNotNull() {
            addCriterion("game_mode is not null");
            return (Criteria) this;
        }

        public Criteria andGameModeEqualTo(Integer value) {
            addCriterion("game_mode =", value, "gameMode");
            return (Criteria) this;
        }

        public Criteria andGameModeNotEqualTo(Integer value) {
            addCriterion("game_mode <>", value, "gameMode");
            return (Criteria) this;
        }

        public Criteria andGameModeGreaterThan(Integer value) {
            addCriterion("game_mode >", value, "gameMode");
            return (Criteria) this;
        }

        public Criteria andGameModeGreaterThanOrEqualTo(Integer value) {
            addCriterion("game_mode >=", value, "gameMode");
            return (Criteria) this;
        }

        public Criteria andGameModeLessThan(Integer value) {
            addCriterion("game_mode <", value, "gameMode");
            return (Criteria) this;
        }

        public Criteria andGameModeLessThanOrEqualTo(Integer value) {
            addCriterion("game_mode <=", value, "gameMode");
            return (Criteria) this;
        }

        public Criteria andGameModeIn(List<Integer> values) {
            addCriterion("game_mode in", values, "gameMode");
            return (Criteria) this;
        }

        public Criteria andGameModeNotIn(List<Integer> values) {
            addCriterion("game_mode not in", values, "gameMode");
            return (Criteria) this;
        }

        public Criteria andGameModeBetween(Integer value1, Integer value2) {
            addCriterion("game_mode between", value1, value2, "gameMode");
            return (Criteria) this;
        }

        public Criteria andGameModeNotBetween(Integer value1, Integer value2) {
            addCriterion("game_mode not between", value1, value2, "gameMode");
            return (Criteria) this;
        }

        public Criteria andJoinAmountIsNull() {
            addCriterion("join_amount is null");
            return (Criteria) this;
        }

        public Criteria andJoinAmountIsNotNull() {
            addCriterion("join_amount is not null");
            return (Criteria) this;
        }

        public Criteria andJoinAmountEqualTo(Integer value) {
            addCriterion("join_amount =", value, "joinAmount");
            return (Criteria) this;
        }

        public Criteria andJoinAmountNotEqualTo(Integer value) {
            addCriterion("join_amount <>", value, "joinAmount");
            return (Criteria) this;
        }

        public Criteria andJoinAmountGreaterThan(Integer value) {
            addCriterion("join_amount >", value, "joinAmount");
            return (Criteria) this;
        }

        public Criteria andJoinAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("join_amount >=", value, "joinAmount");
            return (Criteria) this;
        }

        public Criteria andJoinAmountLessThan(Integer value) {
            addCriterion("join_amount <", value, "joinAmount");
            return (Criteria) this;
        }

        public Criteria andJoinAmountLessThanOrEqualTo(Integer value) {
            addCriterion("join_amount <=", value, "joinAmount");
            return (Criteria) this;
        }

        public Criteria andJoinAmountIn(List<Integer> values) {
            addCriterion("join_amount in", values, "joinAmount");
            return (Criteria) this;
        }

        public Criteria andJoinAmountNotIn(List<Integer> values) {
            addCriterion("join_amount not in", values, "joinAmount");
            return (Criteria) this;
        }

        public Criteria andJoinAmountBetween(Integer value1, Integer value2) {
            addCriterion("join_amount between", value1, value2, "joinAmount");
            return (Criteria) this;
        }

        public Criteria andJoinAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("join_amount not between", value1, value2, "joinAmount");
            return (Criteria) this;
        }

        public Criteria andAdImgIsNull() {
            addCriterion("ad_img is null");
            return (Criteria) this;
        }

        public Criteria andAdImgIsNotNull() {
            addCriterion("ad_img is not null");
            return (Criteria) this;
        }

        public Criteria andAdImgEqualTo(String value) {
            addCriterion("ad_img =", value, "adImg");
            return (Criteria) this;
        }

        public Criteria andAdImgNotEqualTo(String value) {
            addCriterion("ad_img <>", value, "adImg");
            return (Criteria) this;
        }

        public Criteria andAdImgGreaterThan(String value) {
            addCriterion("ad_img >", value, "adImg");
            return (Criteria) this;
        }

        public Criteria andAdImgGreaterThanOrEqualTo(String value) {
            addCriterion("ad_img >=", value, "adImg");
            return (Criteria) this;
        }

        public Criteria andAdImgLessThan(String value) {
            addCriterion("ad_img <", value, "adImg");
            return (Criteria) this;
        }

        public Criteria andAdImgLessThanOrEqualTo(String value) {
            addCriterion("ad_img <=", value, "adImg");
            return (Criteria) this;
        }

        public Criteria andAdImgLike(String value) {
            addCriterion("ad_img like", value, "adImg");
            return (Criteria) this;
        }

        public Criteria andAdImgNotLike(String value) {
            addCriterion("ad_img not like", value, "adImg");
            return (Criteria) this;
        }

        public Criteria andAdImgIn(List<String> values) {
            addCriterion("ad_img in", values, "adImg");
            return (Criteria) this;
        }

        public Criteria andAdImgNotIn(List<String> values) {
            addCriterion("ad_img not in", values, "adImg");
            return (Criteria) this;
        }

        public Criteria andAdImgBetween(String value1, String value2) {
            addCriterion("ad_img between", value1, value2, "adImg");
            return (Criteria) this;
        }

        public Criteria andAdImgNotBetween(String value1, String value2) {
            addCriterion("ad_img not between", value1, value2, "adImg");
            return (Criteria) this;
        }

        public Criteria andAdUrlIsNull() {
            addCriterion("ad_url is null");
            return (Criteria) this;
        }

        public Criteria andAdUrlIsNotNull() {
            addCriterion("ad_url is not null");
            return (Criteria) this;
        }

        public Criteria andAdUrlEqualTo(String value) {
            addCriterion("ad_url =", value, "adUrl");
            return (Criteria) this;
        }

        public Criteria andAdUrlNotEqualTo(String value) {
            addCriterion("ad_url <>", value, "adUrl");
            return (Criteria) this;
        }

        public Criteria andAdUrlGreaterThan(String value) {
            addCriterion("ad_url >", value, "adUrl");
            return (Criteria) this;
        }

        public Criteria andAdUrlGreaterThanOrEqualTo(String value) {
            addCriterion("ad_url >=", value, "adUrl");
            return (Criteria) this;
        }

        public Criteria andAdUrlLessThan(String value) {
            addCriterion("ad_url <", value, "adUrl");
            return (Criteria) this;
        }

        public Criteria andAdUrlLessThanOrEqualTo(String value) {
            addCriterion("ad_url <=", value, "adUrl");
            return (Criteria) this;
        }

        public Criteria andAdUrlLike(String value) {
            addCriterion("ad_url like", value, "adUrl");
            return (Criteria) this;
        }

        public Criteria andAdUrlNotLike(String value) {
            addCriterion("ad_url not like", value, "adUrl");
            return (Criteria) this;
        }

        public Criteria andAdUrlIn(List<String> values) {
            addCriterion("ad_url in", values, "adUrl");
            return (Criteria) this;
        }

        public Criteria andAdUrlNotIn(List<String> values) {
            addCriterion("ad_url not in", values, "adUrl");
            return (Criteria) this;
        }

        public Criteria andAdUrlBetween(String value1, String value2) {
            addCriterion("ad_url between", value1, value2, "adUrl");
            return (Criteria) this;
        }

        public Criteria andAdUrlNotBetween(String value1, String value2) {
            addCriterion("ad_url not between", value1, value2, "adUrl");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(String value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(String value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(String value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(String value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(String value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLike(String value) {
            addCriterion("start_time like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotLike(String value) {
            addCriterion("start_time not like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<String> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<String> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(String value1, String value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(String value1, String value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(String value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(String value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(String value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(String value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(String value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLike(String value) {
            addCriterion("end_time like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotLike(String value) {
            addCriterion("end_time not like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<String> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<String> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(String value1, String value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(String value1, String value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(String value) {
            addCriterion("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(String value) {
            addCriterion("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(String value) {
            addCriterion("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(String value) {
            addCriterion("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(String value) {
            addCriterion("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(String value) {
            addCriterion("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLike(String value) {
            addCriterion("start_date like", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotLike(String value) {
            addCriterion("start_date not like", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<String> values) {
            addCriterion("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<String> values) {
            addCriterion("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(String value1, String value2) {
            addCriterion("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(String value1, String value2) {
            addCriterion("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(String value) {
            addCriterion("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(String value) {
            addCriterion("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(String value) {
            addCriterion("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(String value) {
            addCriterion("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(String value) {
            addCriterion("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(String value) {
            addCriterion("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLike(String value) {
            addCriterion("end_date like", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotLike(String value) {
            addCriterion("end_date not like", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<String> values) {
            addCriterion("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<String> values) {
            addCriterion("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(String value1, String value2) {
            addCriterion("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(String value1, String value2) {
            addCriterion("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andPeriodLengthIsNull() {
            addCriterion("period_length is null");
            return (Criteria) this;
        }

        public Criteria andPeriodLengthIsNotNull() {
            addCriterion("period_length is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodLengthEqualTo(Double value) {
            addCriterion("period_length =", value, "periodLength");
            return (Criteria) this;
        }

        public Criteria andPeriodLengthNotEqualTo(Double value) {
            addCriterion("period_length <>", value, "periodLength");
            return (Criteria) this;
        }

        public Criteria andPeriodLengthGreaterThan(Double value) {
            addCriterion("period_length >", value, "periodLength");
            return (Criteria) this;
        }

        public Criteria andPeriodLengthGreaterThanOrEqualTo(Double value) {
            addCriterion("period_length >=", value, "periodLength");
            return (Criteria) this;
        }

        public Criteria andPeriodLengthLessThan(Double value) {
            addCriterion("period_length <", value, "periodLength");
            return (Criteria) this;
        }

        public Criteria andPeriodLengthLessThanOrEqualTo(Double value) {
            addCriterion("period_length <=", value, "periodLength");
            return (Criteria) this;
        }

        public Criteria andPeriodLengthIn(List<Double> values) {
            addCriterion("period_length in", values, "periodLength");
            return (Criteria) this;
        }

        public Criteria andPeriodLengthNotIn(List<Double> values) {
            addCriterion("period_length not in", values, "periodLength");
            return (Criteria) this;
        }

        public Criteria andPeriodLengthBetween(Double value1, Double value2) {
            addCriterion("period_length between", value1, value2, "periodLength");
            return (Criteria) this;
        }

        public Criteria andPeriodLengthNotBetween(Double value1, Double value2) {
            addCriterion("period_length not between", value1, value2, "periodLength");
            return (Criteria) this;
        }

        public Criteria andCityidIsNull() {
            addCriterion("cityid is null");
            return (Criteria) this;
        }

        public Criteria andCityidIsNotNull() {
            addCriterion("cityid is not null");
            return (Criteria) this;
        }

        public Criteria andCityidEqualTo(Integer value) {
            addCriterion("cityid =", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidNotEqualTo(Integer value) {
            addCriterion("cityid <>", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidGreaterThan(Integer value) {
            addCriterion("cityid >", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cityid >=", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidLessThan(Integer value) {
            addCriterion("cityid <", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidLessThanOrEqualTo(Integer value) {
            addCriterion("cityid <=", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidIn(List<Integer> values) {
            addCriterion("cityid in", values, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidNotIn(List<Integer> values) {
            addCriterion("cityid not in", values, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidBetween(Integer value1, Integer value2) {
            addCriterion("cityid between", value1, value2, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidNotBetween(Integer value1, Integer value2) {
            addCriterion("cityid not between", value1, value2, "cityid");
            return (Criteria) this;
        }

        public Criteria andRenewTimeIsNull() {
            addCriterion("renew_time is null");
            return (Criteria) this;
        }

        public Criteria andRenewTimeIsNotNull() {
            addCriterion("renew_time is not null");
            return (Criteria) this;
        }

        public Criteria andRenewTimeEqualTo(String value) {
            addCriterion("renew_time =", value, "renewTime");
            return (Criteria) this;
        }

        public Criteria andRenewTimeNotEqualTo(String value) {
            addCriterion("renew_time <>", value, "renewTime");
            return (Criteria) this;
        }

        public Criteria andRenewTimeGreaterThan(String value) {
            addCriterion("renew_time >", value, "renewTime");
            return (Criteria) this;
        }

        public Criteria andRenewTimeGreaterThanOrEqualTo(String value) {
            addCriterion("renew_time >=", value, "renewTime");
            return (Criteria) this;
        }

        public Criteria andRenewTimeLessThan(String value) {
            addCriterion("renew_time <", value, "renewTime");
            return (Criteria) this;
        }

        public Criteria andRenewTimeLessThanOrEqualTo(String value) {
            addCriterion("renew_time <=", value, "renewTime");
            return (Criteria) this;
        }

        public Criteria andRenewTimeLike(String value) {
            addCriterion("renew_time like", value, "renewTime");
            return (Criteria) this;
        }

        public Criteria andRenewTimeNotLike(String value) {
            addCriterion("renew_time not like", value, "renewTime");
            return (Criteria) this;
        }

        public Criteria andRenewTimeIn(List<String> values) {
            addCriterion("renew_time in", values, "renewTime");
            return (Criteria) this;
        }

        public Criteria andRenewTimeNotIn(List<String> values) {
            addCriterion("renew_time not in", values, "renewTime");
            return (Criteria) this;
        }

        public Criteria andRenewTimeBetween(String value1, String value2) {
            addCriterion("renew_time between", value1, value2, "renewTime");
            return (Criteria) this;
        }

        public Criteria andRenewTimeNotBetween(String value1, String value2) {
            addCriterion("renew_time not between", value1, value2, "renewTime");
            return (Criteria) this;
        }

        public Criteria andWeekdaysIsNull() {
            addCriterion("weekdays is null");
            return (Criteria) this;
        }

        public Criteria andWeekdaysIsNotNull() {
            addCriterion("weekdays is not null");
            return (Criteria) this;
        }

        public Criteria andWeekdaysEqualTo(String value) {
            addCriterion("weekdays =", value, "weekdays");
            return (Criteria) this;
        }

        public Criteria andWeekdaysNotEqualTo(String value) {
            addCriterion("weekdays <>", value, "weekdays");
            return (Criteria) this;
        }

        public Criteria andWeekdaysGreaterThan(String value) {
            addCriterion("weekdays >", value, "weekdays");
            return (Criteria) this;
        }

        public Criteria andWeekdaysGreaterThanOrEqualTo(String value) {
            addCriterion("weekdays >=", value, "weekdays");
            return (Criteria) this;
        }

        public Criteria andWeekdaysLessThan(String value) {
            addCriterion("weekdays <", value, "weekdays");
            return (Criteria) this;
        }

        public Criteria andWeekdaysLessThanOrEqualTo(String value) {
            addCriterion("weekdays <=", value, "weekdays");
            return (Criteria) this;
        }

        public Criteria andWeekdaysLike(String value) {
            addCriterion("weekdays like", value, "weekdays");
            return (Criteria) this;
        }

        public Criteria andWeekdaysNotLike(String value) {
            addCriterion("weekdays not like", value, "weekdays");
            return (Criteria) this;
        }

        public Criteria andWeekdaysIn(List<String> values) {
            addCriterion("weekdays in", values, "weekdays");
            return (Criteria) this;
        }

        public Criteria andWeekdaysNotIn(List<String> values) {
            addCriterion("weekdays not in", values, "weekdays");
            return (Criteria) this;
        }

        public Criteria andWeekdaysBetween(String value1, String value2) {
            addCriterion("weekdays between", value1, value2, "weekdays");
            return (Criteria) this;
        }

        public Criteria andWeekdaysNotBetween(String value1, String value2) {
            addCriterion("weekdays not between", value1, value2, "weekdays");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andLatLonIsNull() {
            addCriterion("lat_lon is null");
            return (Criteria) this;
        }

        public Criteria andLatLonIsNotNull() {
            addCriterion("lat_lon is not null");
            return (Criteria) this;
        }

        public Criteria andLatLonEqualTo(String value) {
            addCriterion("lat_lon =", value, "latLon");
            return (Criteria) this;
        }

        public Criteria andLatLonNotEqualTo(String value) {
            addCriterion("lat_lon <>", value, "latLon");
            return (Criteria) this;
        }

        public Criteria andLatLonGreaterThan(String value) {
            addCriterion("lat_lon >", value, "latLon");
            return (Criteria) this;
        }

        public Criteria andLatLonGreaterThanOrEqualTo(String value) {
            addCriterion("lat_lon >=", value, "latLon");
            return (Criteria) this;
        }

        public Criteria andLatLonLessThan(String value) {
            addCriterion("lat_lon <", value, "latLon");
            return (Criteria) this;
        }

        public Criteria andLatLonLessThanOrEqualTo(String value) {
            addCriterion("lat_lon <=", value, "latLon");
            return (Criteria) this;
        }

        public Criteria andLatLonLike(String value) {
            addCriterion("lat_lon like", value, "latLon");
            return (Criteria) this;
        }

        public Criteria andLatLonNotLike(String value) {
            addCriterion("lat_lon not like", value, "latLon");
            return (Criteria) this;
        }

        public Criteria andLatLonIn(List<String> values) {
            addCriterion("lat_lon in", values, "latLon");
            return (Criteria) this;
        }

        public Criteria andLatLonNotIn(List<String> values) {
            addCriterion("lat_lon not in", values, "latLon");
            return (Criteria) this;
        }

        public Criteria andLatLonBetween(String value1, String value2) {
            addCriterion("lat_lon between", value1, value2, "latLon");
            return (Criteria) this;
        }

        public Criteria andLatLonNotBetween(String value1, String value2) {
            addCriterion("lat_lon not between", value1, value2, "latLon");
            return (Criteria) this;
        }

        public Criteria andAddrRangeIsNull() {
            addCriterion("addr_range is null");
            return (Criteria) this;
        }

        public Criteria andAddrRangeIsNotNull() {
            addCriterion("addr_range is not null");
            return (Criteria) this;
        }

        public Criteria andAddrRangeEqualTo(String value) {
            addCriterion("addr_range =", value, "addrRange");
            return (Criteria) this;
        }

        public Criteria andAddrRangeNotEqualTo(String value) {
            addCriterion("addr_range <>", value, "addrRange");
            return (Criteria) this;
        }

        public Criteria andAddrRangeGreaterThan(String value) {
            addCriterion("addr_range >", value, "addrRange");
            return (Criteria) this;
        }

        public Criteria andAddrRangeGreaterThanOrEqualTo(String value) {
            addCriterion("addr_range >=", value, "addrRange");
            return (Criteria) this;
        }

        public Criteria andAddrRangeLessThan(String value) {
            addCriterion("addr_range <", value, "addrRange");
            return (Criteria) this;
        }

        public Criteria andAddrRangeLessThanOrEqualTo(String value) {
            addCriterion("addr_range <=", value, "addrRange");
            return (Criteria) this;
        }

        public Criteria andAddrRangeLike(String value) {
            addCriterion("addr_range like", value, "addrRange");
            return (Criteria) this;
        }

        public Criteria andAddrRangeNotLike(String value) {
            addCriterion("addr_range not like", value, "addrRange");
            return (Criteria) this;
        }

        public Criteria andAddrRangeIn(List<String> values) {
            addCriterion("addr_range in", values, "addrRange");
            return (Criteria) this;
        }

        public Criteria andAddrRangeNotIn(List<String> values) {
            addCriterion("addr_range not in", values, "addrRange");
            return (Criteria) this;
        }

        public Criteria andAddrRangeBetween(String value1, String value2) {
            addCriterion("addr_range between", value1, value2, "addrRange");
            return (Criteria) this;
        }

        public Criteria andAddrRangeNotBetween(String value1, String value2) {
            addCriterion("addr_range not between", value1, value2, "addrRange");
            return (Criteria) this;
        }

        public Criteria andFakeAmountIsNull() {
            addCriterion("fake_amount is null");
            return (Criteria) this;
        }

        public Criteria andFakeAmountIsNotNull() {
            addCriterion("fake_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFakeAmountEqualTo(Integer value) {
            addCriterion("fake_amount =", value, "fakeAmount");
            return (Criteria) this;
        }

        public Criteria andFakeAmountNotEqualTo(Integer value) {
            addCriterion("fake_amount <>", value, "fakeAmount");
            return (Criteria) this;
        }

        public Criteria andFakeAmountGreaterThan(Integer value) {
            addCriterion("fake_amount >", value, "fakeAmount");
            return (Criteria) this;
        }

        public Criteria andFakeAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("fake_amount >=", value, "fakeAmount");
            return (Criteria) this;
        }

        public Criteria andFakeAmountLessThan(Integer value) {
            addCriterion("fake_amount <", value, "fakeAmount");
            return (Criteria) this;
        }

        public Criteria andFakeAmountLessThanOrEqualTo(Integer value) {
            addCriterion("fake_amount <=", value, "fakeAmount");
            return (Criteria) this;
        }

        public Criteria andFakeAmountIn(List<Integer> values) {
            addCriterion("fake_amount in", values, "fakeAmount");
            return (Criteria) this;
        }

        public Criteria andFakeAmountNotIn(List<Integer> values) {
            addCriterion("fake_amount not in", values, "fakeAmount");
            return (Criteria) this;
        }

        public Criteria andFakeAmountBetween(Integer value1, Integer value2) {
            addCriterion("fake_amount between", value1, value2, "fakeAmount");
            return (Criteria) this;
        }

        public Criteria andFakeAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("fake_amount not between", value1, value2, "fakeAmount");
            return (Criteria) this;
        }

        public Criteria andFakeSuccessPercentageIsNull() {
            addCriterion("fake_success_percentage is null");
            return (Criteria) this;
        }

        public Criteria andFakeSuccessPercentageIsNotNull() {
            addCriterion("fake_success_percentage is not null");
            return (Criteria) this;
        }

        public Criteria andFakeSuccessPercentageEqualTo(Integer value) {
            addCriterion("fake_success_percentage =", value, "fakeSuccessPercentage");
            return (Criteria) this;
        }

        public Criteria andFakeSuccessPercentageNotEqualTo(Integer value) {
            addCriterion("fake_success_percentage <>", value, "fakeSuccessPercentage");
            return (Criteria) this;
        }

        public Criteria andFakeSuccessPercentageGreaterThan(Integer value) {
            addCriterion("fake_success_percentage >", value, "fakeSuccessPercentage");
            return (Criteria) this;
        }

        public Criteria andFakeSuccessPercentageGreaterThanOrEqualTo(Integer value) {
            addCriterion("fake_success_percentage >=", value, "fakeSuccessPercentage");
            return (Criteria) this;
        }

        public Criteria andFakeSuccessPercentageLessThan(Integer value) {
            addCriterion("fake_success_percentage <", value, "fakeSuccessPercentage");
            return (Criteria) this;
        }

        public Criteria andFakeSuccessPercentageLessThanOrEqualTo(Integer value) {
            addCriterion("fake_success_percentage <=", value, "fakeSuccessPercentage");
            return (Criteria) this;
        }

        public Criteria andFakeSuccessPercentageIn(List<Integer> values) {
            addCriterion("fake_success_percentage in", values, "fakeSuccessPercentage");
            return (Criteria) this;
        }

        public Criteria andFakeSuccessPercentageNotIn(List<Integer> values) {
            addCriterion("fake_success_percentage not in", values, "fakeSuccessPercentage");
            return (Criteria) this;
        }

        public Criteria andFakeSuccessPercentageBetween(Integer value1, Integer value2) {
            addCriterion("fake_success_percentage between", value1, value2, "fakeSuccessPercentage");
            return (Criteria) this;
        }

        public Criteria andFakeSuccessPercentageNotBetween(Integer value1, Integer value2) {
            addCriterion("fake_success_percentage not between", value1, value2, "fakeSuccessPercentage");
            return (Criteria) this;
        }

        public Criteria andIsHideIsNull() {
            addCriterion("is_hide is null");
            return (Criteria) this;
        }

        public Criteria andIsHideIsNotNull() {
            addCriterion("is_hide is not null");
            return (Criteria) this;
        }

        public Criteria andIsHideEqualTo(Integer value) {
            addCriterion("is_hide =", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideNotEqualTo(Integer value) {
            addCriterion("is_hide <>", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideGreaterThan(Integer value) {
            addCriterion("is_hide >", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_hide >=", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideLessThan(Integer value) {
            addCriterion("is_hide <", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideLessThanOrEqualTo(Integer value) {
            addCriterion("is_hide <=", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideIn(List<Integer> values) {
            addCriterion("is_hide in", values, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideNotIn(List<Integer> values) {
            addCriterion("is_hide not in", values, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideBetween(Integer value1, Integer value2) {
            addCriterion("is_hide between", value1, value2, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideNotBetween(Integer value1, Integer value2) {
            addCriterion("is_hide not between", value1, value2, "isHide");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("sort is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("sort is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("sort =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("sort <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("sort >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("sort >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("sort <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("sort <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Integer> values) {
            addCriterion("sort in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Integer> values) {
            addCriterion("sort not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("sort between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("sort not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andRecommendIsNull() {
            addCriterion("recommend is null");
            return (Criteria) this;
        }

        public Criteria andRecommendIsNotNull() {
            addCriterion("recommend is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendEqualTo(Integer value) {
            addCriterion("recommend =", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendNotEqualTo(Integer value) {
            addCriterion("recommend <>", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendGreaterThan(Integer value) {
            addCriterion("recommend >", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendGreaterThanOrEqualTo(Integer value) {
            addCriterion("recommend >=", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendLessThan(Integer value) {
            addCriterion("recommend <", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendLessThanOrEqualTo(Integer value) {
            addCriterion("recommend <=", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendIn(List<Integer> values) {
            addCriterion("recommend in", values, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendNotIn(List<Integer> values) {
            addCriterion("recommend not in", values, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendBetween(Integer value1, Integer value2) {
            addCriterion("recommend between", value1, value2, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendNotBetween(Integer value1, Integer value2) {
            addCriterion("recommend not between", value1, value2, "recommend");
            return (Criteria) this;
        }

        public Criteria andPrivalageIsNull() {
            addCriterion("privalage is null");
            return (Criteria) this;
        }

        public Criteria andPrivalageIsNotNull() {
            addCriterion("privalage is not null");
            return (Criteria) this;
        }

        public Criteria andPrivalageEqualTo(Integer value) {
            addCriterion("privalage =", value, "privalage");
            return (Criteria) this;
        }

        public Criteria andPrivalageNotEqualTo(Integer value) {
            addCriterion("privalage <>", value, "privalage");
            return (Criteria) this;
        }

        public Criteria andPrivalageGreaterThan(Integer value) {
            addCriterion("privalage >", value, "privalage");
            return (Criteria) this;
        }

        public Criteria andPrivalageGreaterThanOrEqualTo(Integer value) {
            addCriterion("privalage >=", value, "privalage");
            return (Criteria) this;
        }

        public Criteria andPrivalageLessThan(Integer value) {
            addCriterion("privalage <", value, "privalage");
            return (Criteria) this;
        }

        public Criteria andPrivalageLessThanOrEqualTo(Integer value) {
            addCriterion("privalage <=", value, "privalage");
            return (Criteria) this;
        }

        public Criteria andPrivalageIn(List<Integer> values) {
            addCriterion("privalage in", values, "privalage");
            return (Criteria) this;
        }

        public Criteria andPrivalageNotIn(List<Integer> values) {
            addCriterion("privalage not in", values, "privalage");
            return (Criteria) this;
        }

        public Criteria andPrivalageBetween(Integer value1, Integer value2) {
            addCriterion("privalage between", value1, value2, "privalage");
            return (Criteria) this;
        }

        public Criteria andPrivalageNotBetween(Integer value1, Integer value2) {
            addCriterion("privalage not between", value1, value2, "privalage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}