package com.twq.dao.mapper;

import com.twq.dao.model.ContentInfo;
import com.twq.dao.model.ContentInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ContentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    long countByExample(ContentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int deleteByExample(ContentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int insert(ContentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int insertSelective(ContentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    List<ContentInfo> selectByExample(ContentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ContentInfo record, @Param("example") ContentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ContentInfo record, @Param("example") ContentInfoExample example);
}