package com.twq.dao.mapper;

import com.twq.dao.model.GameWallet;
import com.twq.dao.model.GameWalletExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GameWalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_wallet
     *
     * @mbg.generated
     */
    long countByExample(GameWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_wallet
     *
     * @mbg.generated
     */
    int deleteByExample(GameWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_wallet
     *
     * @mbg.generated
     */
    int insert(GameWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_wallet
     *
     * @mbg.generated
     */
    int insertSelective(GameWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_wallet
     *
     * @mbg.generated
     */
    List<GameWallet> selectByExample(GameWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_wallet
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GameWallet record, @Param("example") GameWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_wallet
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GameWallet record, @Param("example") GameWalletExample example);
}