package com.twq.dao.mapper;

import com.twq.dao.model.Games;
import com.twq.dao.model.GamesExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GamesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games
     *
     * @mbg.generated
     */
    long countByExample(GamesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games
     *
     * @mbg.generated
     */
    int deleteByExample(GamesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games
     *
     * @mbg.generated
     */
    int insert(Games record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games
     *
     * @mbg.generated
     */
    int insertSelective(Games record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games
     *
     * @mbg.generated
     */
    List<Games> selectByExample(GamesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games
     *
     * @mbg.generated
     */
    Games selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Games record, @Param("example") GamesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Games record, @Param("example") GamesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Games record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table games
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Games record);
}