package com.twq.dao.mapper;

import com.twq.dao.model.Parameters;
import com.twq.dao.model.ParametersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParametersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameters
     *
     * @mbg.generated
     */
    long countByExample(ParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameters
     *
     * @mbg.generated
     */
    int deleteByExample(ParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameters
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String paramKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameters
     *
     * @mbg.generated
     */
    int insert(Parameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameters
     *
     * @mbg.generated
     */
    int insertSelective(Parameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameters
     *
     * @mbg.generated
     */
    List<Parameters> selectByExample(ParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameters
     *
     * @mbg.generated
     */
    Parameters selectByPrimaryKey(String paramKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameters
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Parameters record, @Param("example") ParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameters
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Parameters record, @Param("example") ParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameters
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Parameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameters
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Parameters record);
}