package com.twq.dao.mapper;

import com.twq.dao.model.UserWallet;
import com.twq.dao.model.UserWalletExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserWalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated
     */
    long countByExample(UserWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated
     */
    int deleteByExample(UserWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated
     */
    int insert(UserWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated
     */
    int insertSelective(UserWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated
     */
    List<UserWallet> selectByExample(UserWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated
     */
    UserWallet selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserWallet record, @Param("example") UserWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserWallet record, @Param("example") UserWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserWallet record);
}